export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_CREDITS = 'FETCH_CREDITS';
export const DELETE_STATE = 'DELETE_STATE';

export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const DELETE_FROM_WATCHLIST = 'DELETE_FROM_WATCHLIST';
export const FETCH_WATCHLIST = 'FETCH_WATCHLIST';
