export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

//movie reducer
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_CREDITS = 'FETCH_CREDITS';
export const DELETE_SINGLE_MOVIE_STATE = 'DELETE_SINGLE_MOVIE_STATE';
export const DELETE_WATCHLIST_ITEM_FROM_MOVIES = 'DELETE_WATCHLIST_ITEM_FROM_MOVIES';
export const FETCH_TRAILER = 'FETCH_TRAILER';

//watchlist reducer
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const DELETE_FROM_WATCHLIST = 'DELETE_FROM_WATCHLIST';
export const FETCH_WATCHLIST = 'FETCH_WATCHLIST';
export const FETCH_WATCHLIST_MOVIES = 'FETCH_WATCHLIST_MOVIES';
export const DELTE_WATCHLIST = 'DELTE_WATCHLIST';

//searchbar reducer
export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const CHANGE_IS_LOADING = 'CHANGE_IS_LOADING';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_TO_SHOW = 'SET_TO_SHOW';
